[package]
name = "activite"
version = "0.1.0"
entrypoint = "src/main.typ"
authors = ["RV"]
description = "A simple Typst package for managing localized text."
license = "MIT" # Or choose another appropriate license
